version: '3.8'

services:
  go-rest:
    container_name: go-rest
    build:
      context: ./docker/golang
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./
        target: /go/src
    restart: always

  db:
    container_name: db
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3309:3306
    env_file:
      - .env
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql
    restart: always

volumes:
  mysql:

